name: ncp
channels:
  - conda-forge
dependencies:
  - pip=20.2.4
  - conda-forge::pandas>=1.5.2
  - conda-forge::jupyter=1.0.0
  # - conda-forge::numpy=1.23.5
  - conda-forge::ipykernel=6.19.2
  # - conda-forge::widgetsnbextension=3.5.1
  - conda-forge::matplotlib>=3.6.2
  # - conda-forge::matplotlib-venn=0.11.6
  # - conda-forge::scikit-learn=0.23.2
  # - conda-forge::scipy=1.8.0
  - conda-forge::seaborn>=0.11.0
  # - conda-forge::statsmodels=0.12.0
  # - conda-forge::plotly=5.17.0
  # - conda-forge::python-kaleido=0.2.1
  - conda-forge::nb_black=1.0.7
  - conda-forge::pyarrow>=8.0.0
  - conda-forge::python=3.9.15
  - conda-forge::scikit-learn>=1.3.1
  - pip:
      - git+https://github.com/cytomining/pycytominer@v1.0.0
      - git+https://github.com/cytomining/cytominer-database@v0.3.4
      - git+https://github.com/cytomining/copairs@v0.3.0
  #     - git+https://github.com/cytomining/cytominer-eval@f7f5b293da54d870e8ba86bacf7dbc874bb79565
