name: ncp_test
channels:
- conda-forge
dependencies:
- pip=20.2.4
- conda-forge::pandas=1.1.3
- conda-forge::jupyter=1.0.0
- conda-forge::numpy=1.19.2
- conda-forge::ipykernel=5.3.4
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::matplotlib=3.3.2
- conda-forge::matplotlib-venn=0.11.6
- conda-forge::scikit-learn=0.23.2
- conda-forge::scipy=1.5.2
- conda-forge::seaborn=0.11.0
- conda-forge::statsmodels=0.12.0
- pip:
  - git+https://github.com/cytomining/pycytominer@838ac2eee8bee09b50a1ec8077201c01f7882c69
  - git+https://github.com/cytomining/cytominer-eval@f7f5b293da54d870e8ba86bacf7dbc874bb79565