---
title: "Sample wells"
output: github_document
---

Select a few wells from each condition from the `CELLPAINTING` platemap.

```{r load_libraries, message=FALSE}
library(magrittr)
library(tidyverse)
```

```{r load_platemap}
platemap <- read_tsv("metadata/platemaps/CELLPAINTING.txt")

platemap %<>% mutate(condition_density = interaction(condition, plating_density))
```

Display the platemap

```{r display_platemap}
p <- 
  platetools::raw_map(data =
                      as.character(platemap$condition_density),
                      well = platemap$well_position,
                      plate = 384) +
  theme_dark() +
  scale_fill_discrete()

print(p)
```
Sample a few wells (per condition) to analyze

```{r display_platemap_reduced}
platemap_reduced <- 
  platemap %>% 
  mutate(condition_density = 
    case_when(
      str_detect(well_position, "^C|^D|^L|^M") & str_detect(well_position, "02$|03$|10$|11$|18$|19$") ~ as.character(condition_density),
      TRUE ~ "0SKIP"
    )
    )

p <- 
  platetools::raw_map(
    data = as.character(platemap_reduced$condition_density),
    well = platemap_reduced$well_position,
    plate = 384) +
  theme_dark() +
  scale_fill_discrete()

print(p)
```


Display list of wells

```{r display_platemap_reduced_df}
platemap_reduced %>% 
  filter(condition_density != "0SKIP") %>%
  select(well_position, plating_density, condition) %>%
  data.frame()
```

Make a list of corresponding images

```{r}
load_data <- 
  read_csv("../../../load_data_csv/NCP_PILOT_1/BR00106976/load_data.csv") %>%
  select(-matches("Brightfield")) %>% 
  inner_join(platemap_reduced %>% 
               filter(condition_density != "0SKIP") %>% 
               select(well_position),
             by = c("Metadata_Well" = "well_position")) 

load_data %>%
  write_csv("output/subset_BR00106975_load_data.csv")

load_data %>%
  mutate(PathName_OrigAGP  = str_replace(PathName_OrigAGP,  "/home/ubuntu/bucket", "s3://imaging-platform")) %>%
  mutate(PathName_OrigDNA  = str_replace(PathName_OrigDNA,  "/home/ubuntu/bucket", "s3://imaging-platform")) %>%
  mutate(PathName_OrigER   = str_replace(PathName_OrigER,   "/home/ubuntu/bucket", "s3://imaging-platform")) %>%
  mutate(PathName_OrigMito = str_replace(PathName_OrigMito, "/home/ubuntu/bucket", "s3://imaging-platform")) %>%
  mutate(PathName_OrigRNA  = str_replace(PathName_OrigRNA,  "/home/ubuntu/bucket", "s3://imaging-platform")) %>%
  mutate(S3_OrigAGP  = str_c(PathName_OrigAGP , "/", FileName_OrigAGP )) %>%
  mutate(S3_OrigDNA  = str_c(PathName_OrigDNA , "/", FileName_OrigDNA )) %>%
  mutate(S3_OrigER   = str_c(PathName_OrigER  , "/", FileName_OrigER  )) %>%
  mutate(S3_OrigMito = str_c(PathName_OrigMito, "/", FileName_OrigMito)) %>%
  mutate(S3_OrigRNA  = str_c(PathName_OrigRNA , "/", FileName_OrigRNA )) %>% 
  select(matches("^S3")) %>%
  gather(channel, s3loc) %>%
  select(s3loc) %>%
  write_tsv("output/subset_BR00106975_files.txt", col_names = FALSE)
```

Copy these files locally. 
Replace the paths below as appropriate.

```
mkdir -p ~/work/projects/2019_05_28_Neuronal_Cell_Painting/NCP_PILOT_1/images/BR00106976__2019-08-26T17_45_18-Measurement_1/Images/
parallel -a output/subset_BR00106975_files.txt aws s3 cp {1} ~/work/projects/2019_05_28_Neuronal_Cell_Painting/NCP_PILOT_1/images/BR00106976__2019-08-26T17_45_18-Measurement_1/Images/
```

Create a load data file with relative paths. Edit `project_base_path` as appropriate.

```{r}
project_base_path <- path.expand("~/work/projects/2019_05_28_Neuronal_Cell_Painting/")
  
read_csv("output/subset_BR00106975_load_data.csv") %>%
  mutate(PathName_OrigAGP  = str_replace(PathName_OrigAGP,  "/home/ubuntu/bucket/projects/2019_05_28_Neuronal_Cell_Painting/", project_base_path)) %>%
  mutate(PathName_OrigDNA  = str_replace(PathName_OrigDNA,  "/home/ubuntu/bucket/projects/2019_05_28_Neuronal_Cell_Painting/", project_base_path)) %>%
  mutate(PathName_OrigER   = str_replace(PathName_OrigER,   "/home/ubuntu/bucket/projects/2019_05_28_Neuronal_Cell_Painting/", project_base_path)) %>%
  mutate(PathName_OrigMito = str_replace(PathName_OrigMito, "/home/ubuntu/bucket/projects/2019_05_28_Neuronal_Cell_Painting/", project_base_path)) %>%
  mutate(PathName_OrigRNA  = str_replace(PathName_OrigRNA,  "/home/ubuntu/bucket/projects/2019_05_28_Neuronal_Cell_Painting/", project_base_path)) %>%
  write_csv(path.expand("~/Desktop/subset_BR00106975_load_data_local.csv"))
```

